artifacts_dir: artifacts

data_ingestion:
  dataset_dir: data
  dataset_name: predictive_maintenance.csv
  raw_data_dir: raw_data
  train_dir: train
  test_dir: test

data_validation:
  schema_file: config/schema.yaml
  validation_report_dir: validation
  validation_report_file: validation_report.yaml

data_transformation:
  preprocessor_dir: preprocessor
  preprocessor_name: preprocessor.pkl
  transformed_dir: transformed
  train_array_name: train.npy
  test_array_name: test.npy

model_trainer:
  model_trainer:
  trained_model_dir: model
  trained_model_name: trained_model.pkl
  expected_accuracy: 0.70
  overfitting_underfitting_threshold: 0.10